on:
  push:
    branches:
      - master

jobs:
  update_master-fake:
    runs-on: ubuntu-latest
    env:
      REPO: ${{github.actor}}:${{secrets.ACCESS_TOKEN}}@github.com/${{github.repository}}.git
    steps:
      - run: |
          echo $REPO
          git config --global user.email "someone@sample.com"
          git config --global user.name "github workflow"
          git clone "https://${REPO}"
          git branch -a
          git checkout origin/master-fake
          git merge origin/master && git push "https://${REPO}" master-fake
